parameters:
    service_are_public: false

    sylar_data_path_default: /app/data
    sylar_data_path: '%env(default:sylar_data_path_default:SYLAR_DATA_PATH)%'

    sylar_config_filename_default: '%sylar_data_path%/sylar.yaml'
    sylar_config_filename: '%env(default:sylar_config_filename_default:SYLAR_CONFIG_FILENAME)%'

    default_supervisord_url: 'http://127.0.0.1:9001'
    default_supervisord_user: 'admin'
    default_supervisord_password: 'adminpass'

    supervisord_url: '%env(default:default_supervisord_url:SUPERVISORD_URL)%'
    supervisord_user: '%env(default:default_supervisord_user:SUPERVISORD_USER)%'
    supervisord_password: '%env(default:default_supervisord_password:SUPERVISORD_PASSWORD)%'
    mounted_configuration_path_default: /opt/sylar/data
    mounted_configuration_path: '%env(default:mounted_configuration_path_default:SYLAR_MOUNTED_CONFIGURATION_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: '%service_are_public%'
        bind:
            $configurationFilename: '%sylar_config_filename%'
            $mountedConfigurationPath: '%mounted_configuration_path%'
            $containerConfigurationPath: '/app/data'
            $containerDatabasePath: '/app/data/database'
            $dockerReadOnly: '@docker.readonly'
            $dockerReadWrite: '@docker.readwrite'

    App\:
        resource: '../../src/*'
        exclude:
         - '../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
         - '../../src/**/Core/ServiceCloner/Reservation/Object/*.php'
         - '../../src/**/Core/ServiceCloner/Configuration/Object/*.php'
         - '../../src/**/*DTO.php'
         - '../../src/**/*Exception.php'
         - '../../src/**/*Command.php'

    App\UserInterface\Cli\:
        resource: '../../src/UserInterface/Cli/**Command.php'
        tags: ['console.command']

    docker.readwrite:
        class: Docker\Docker
        factory: ['@App\Infrastructure\Docker\DockerFactory', 'create']
        arguments:
            $dockerRemoteSocket: 'unix:///var/run/docker.sock'

    docker.readonly:
        class: Docker\Docker
        factory: ['@App\Infrastructure\Docker\DockerFactory', 'create']
        arguments:
            $dockerRemoteSocket: 'http://docker-socket-proxy:2375'

    App\UserInterface\GraphQL\ResolverMap\:
        resource: '%kernel.project_dir%/src/UserInterface/GraphQL/ResolverMap'
        tags: [{ name: overblog_graphql.resolver_map, schema: default }]

    App\Infrastructure\PostContainerDumpActions\PostContainerDumpServiceInterface: '@App\Infrastructure\PostContainerDumpActions\PostContainerDumpService'

    App\UserInterface\Cli\RestartSupervisordWorkersCommand:
        arguments:
            $supervisordUrl: '%supervisord_url%/RPC2'
            $supervisordUser: '%supervisord_user%'
            $supervisordPassword: '%supervisord_password%'

    App\Infrastructure\Process\ProcessInterface: '@App\Infrastructure\Process\Process'

    App\Infrastructure\Messenger\FailedMessages\Repository\FailedMessagesRepository:
        arguments:
            $receiver: '@messenger.transport.failed'

    App\Infrastructure\Messenger\FailedMessages\Graphql\Mutation\MutationRejectMessage:
        arguments:
            $receiver: '@messenger.transport.failed'

    App\Infrastructure\Messenger\FailedMessages\Graphql\Mutation\MutationRetryMessage:
        arguments:
            $receiver: '@messenger.transport.failed'

    App\Infrastructure\Logging\ServerSideEventPublisherHandler:
        arguments:
            $level: WARNING
            $bubble: false

    Itspire\MonologLoki\Handler\LokiHandler:
        arguments:
            $apiConfig:
                entrypoint: 'http://loki:3100'
                context:
                    app: sylar
                labels:
                    env: '%env(APP_ENV)%'
                client_name: runner
                curl_options:
                    !php/const CURLOPT_CONNECTTIMEOUT_MS: 500,
                    !php/const CURLOPT_TIMEOUT_MS: 600
