parameters:
    service_are_public: false

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: '%service_are_public%'

    App\:
        resource: '../../src/*'
        exclude:
         - '../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
         - '../../src/**/*DTO.php'

    App\UserInterface\Cli\:
        resource: '../../src/UserInterface/Cli/**'
        tags: ['console.command']

    App\Infrastructure\Filesystem\ZfsFilesystemService:
        arguments:
            $process : '@App\Infrastructure\Process\SudoProcess'
