parameters:
    service_are_public: false

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: '%service_are_public%'

    App\:
        resource: '../../src/*'
        exclude:
         - '../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
         - '../../src/Infrastructure/Zfs/*DTO.php'

    App\UserInterface\Cli\:
        resource: '../../src/UserInterface/Cli/**'
        tags: ['console.command']

    App\Infrastructure\Zfs\ZfsService:
        arguments:
            $process : '@App\Infrastructure\Process\SudoProcess'

    Docker\Docker:
        factory: ['@App\Infrastructure\Docker\DockerFactory', 'create']
