parameters:
    service_are_public: false

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: '%service_are_public%'

    App\:
        resource: '../../src/*'
        exclude:
         - '../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\UserInterface\Cli\:
        resource: '../../src/UserInterface/Cli/**'
        tags: ['console.command']
