---
- hosts: all
  become: true
  vars:
    - NODEJS_VERSION: "12"
    - ansible_distribution_release: "bionic"

  tasks:
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present

    - name: Add Yarn GPG apt Key
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: Add Yarn Repository
      apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        state: present

    - name: Additional PPA for php
      apt_repository:
        validate_certs: no
        repo: 'ppa:ondrej/php'
        state: present
        update_cache: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present

    - name: Install yarn
      apt:
        name: yarn
        state: latest

    - name: remove 7.3
      apt: name={{ item }} state=absent
      loop:
        - 'php7.3-common'

    - name: Install required system packages
      apt: name={{ item }} state=latest
      loop:
        - 'php7.4-cli'
        - 'php7.4-curl'
        - 'php7.4-json'
        - 'php7.4-sqlite3'
        - 'php7.4-zip'
        - 'php7.4-xml'
        - 'php7.4-mbstring'
        - 'php7.4-fpm'

    - name: adding existing user 'vagrant' to group www-data
      user:
        name: 'vagrant'
        groups:
          - www-data
        append: yes
