---
- hosts: all
  become: true
  vars_files:
      - ../vars/mysql-slave-vars.yml

  tasks:
    - name: Check slave replication status.
      mysql_replication:
        mode: getslave
        login_user: "{{ mysql_replication_user.name }}"
        login_password: "{{ mysql_replication_user.password }}"
      ignore_errors: true
      register: slave
      when:
        - (mysql_replication_master | length) > 0
      tags: ['skip_ansible_galaxy']

    - name: Configure replication on the slave.
      mysql_replication:
        mode: changemaster
        master_host: "{{ mysql_replication_master }}"
        master_user: "{{ mysql_replication_user.name }}"
        master_password: "{{ mysql_replication_user.password }}"
        #master_log_file: "{{ master.File }}"
        #master_log_pos: "{{ master.Position }}"
      ignore_errors: true
      when:
        - mysql_replication_user.name is defined
        - (mysql_replication_master | length) > 0

    - name: Start replication.
      mysql_replication: mode=startslave
      when:
        - (mysql_replication_master | length) > 0
      tags: ['skip_ansible_galaxy']
