---
- hosts: all
  become: true
  vars_files:
      - ../vars/mysql-slave-vars.yml

  tasks:
      - name: Stop replication
        ansible.builtin.shell:
          cmd: mysql -u root -p{{ mysql_root_password }} -h 127.0.0.1 -e "STOP SLAVE;" || true

      - name: set replication user
        ansible.builtin.shell:
          cmd: mysql -u root -p{{ mysql_root_password }} -h 127.0.0.1 -e "GRANT REPLICATION SLAVE ON *.* TO '{{ mysql_replication_user.name }}'@'%' IDENTIFIED BY '{{ mysql_replication_user.password }}';" || true

      - name: Set replication user
        ansible.builtin.shell:
          cmd: mysql -u root -p{{ mysql_root_password }} -h 127.0.0.1 -e "CHANGE MASTER TO MASTER_HOST='{{ mysql_replication_master }}', MASTER_USER='{{ mysql_replication_user.name }}', MASTER_PASSWORD='{{ mysql_replication_user.password }}';" || true

      - name: Start replication
        ansible.builtin.shell:
          cmd: mysql -u root -p{{ mysql_root_password }} -h 127.0.0.1 -e "START SLAVE;" || true

