---
- hosts: all
  become: true
  vars:
    - ansible_distribution_release: "bionic"

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest
      loop:
        - 'apt-transport-https'
        - 'ca-certificates'
        - 'curl'
        - 'software-properties-common'
        - 'python3-pip'
        - 'virtualenv'
        - 'python3-setuptools'
