---
- hosts: all
  become: true
  post_tasks:
    - name: Create zfs pool
      ansible.builtin.shell:
        cmd: sudo zpool create sylar /dev/sdc || true

  vars:
    - role: ansible-zfs

  tasks:
    - name: Install required zfs packages
      apt:
        name: zfsutils-linux
        state: latest
        update_cache: yes
