overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: Mutations
        mappings:
            types:
                - type: yaml
                  dir: "%kernel.project_dir%/config/graphql/types"
                  suffix: null
                - type: yaml
                  dir: "%kernel.project_dir%/src/Infrastructure/Messenger/FailedMessages/Graphql/Type"
                  suffix: null
