monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: loki
            level: info
            channels: ["!event", "!doctrine"]
        console:
            type: console
            handler: loki
            level: info
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        security:
            type: stream
            level: info
            handler: loki
            channels: ["php"]
        loki:
            type: service
            level: info
            id: Itspire\MonologLoki\Handler\LokiHandler
            channels: ["!event", "!doctrine", "!console"]
