api_login_check:
  path: /api/login_check

controllers:
  resource:
    path: ../../src/UserInterface/Web/UseCase/
    namespace: App\UserInterface\Web\UseCase
  type: attribute

kernel:
  resource: App\Kernel
  type: attribute
