FROM node:alpine3.13

#ARG NODE_ENV
#ENV NODE_ENV ${NODE_ENV}

# Install common dependencies
#RUN apt-get update \
#  && apt-get install -y net-tools \
#  && apt-get clean \
#  && rm -rf /var/lib/apt/lists/*
#
## Install Yarn
#RUN curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3 && \
#  ln -sf $HOME/.yarn/bin/yarn /usr/local/bin/yarn && \
#  ln -sf $HOME/.yarn/bin/yarnpkg /usr/local/bin/yarnpkg

RUN apk add yarn

