monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            handler: loki
            level: debug
            channels: ["!event", "!doctrine"]
        console:
            type: console
            handler: loki
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        security:
            level: DEBUG
            type: stream
            handler: loki
            channels: [php]
