global:
  scrape_interval: 5s
  external_labels:
    monitor: 'prakash-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['sylar-prometheus:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['sylar-node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['sylar-cadvisor:8080']
