monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            path: "php://stderr"
            excluded_http_codes: [404, 405]
            buffer_size: 50
        syslog_handler:
            type: syslog
            level: error
        console:
            type: console
            level: debug
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
