---
- hosts: all
  become: true
  vars:
    - role: ansible-zfs
    - NODEJS_VERSION: "11"
    - ansible_distribution_release: "bionic"

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop:
        - 'apt-transport-https'
        - 'ca-certificates'
        - 'curl'
        - 'software-properties-common'
        - 'python3-pip'
        - 'virtualenv'
        - 'python3-setuptools'

    - name: Install required zfs packages
      apt:
        name: zfsutils-linux
        state: latest
        update_cache: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: adding existing user 'vagrant' to group docker
      user:
        name: 'vagrant'
        groups:
          - docker
        append: yes
