---
- hosts: master
  become: true
  pre_tasks:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars/mysql-master-vars.yml
  roles:
    - { role: geerlingguy.mysql }

- name: Vagrant system
  import_playbook: playbooks/system.yml

- name: Vagrant mysql master
  import_playbook: playbooks/mysql-master.yml

