---
- hosts: slave
  become: true
  vars_files:
    - vars/mysql-slave-vars.yml
  roles:
    - { role: geerlingguy.mysql }

- name: Vagrant system
  import_playbook: playbooks/system.yml

- name: Vagrant docker
  import_playbook: playbooks/docker.yml

- name: Vagrant zfs
  import_playbook: playbooks/zfs.yml

- name: Vagrant dev tools
  import_playbook: playbooks/dev.yml

- name: Vagrant nginx
  import_playbook: playbooks/nginx.yml

- name: Vagrant supervisor
  import_playbook: playbooks/supervisor.yml

- name: Vagrant mysql slave
  import_playbook: playbooks/mysql-slave.yml
