---
- hosts: slave
  become: true

  roles:
    - role: gantsign.antigen
      users:
        - username: vagrant
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: agnoster
          antigen_bundles:
            - name: git
            - name: docker
            - name: command-not-found
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting

- name: Vagrant system
  import_playbook: playbooks/system.yml

- name: Vagrant docker
  import_playbook: playbooks/docker.yml

- name: Vagrant zfs
  import_playbook: playbooks/zfs.yml
